# Create certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vikunja-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: vikunja-secret
  issuerRef:
    name: {{ .Values.ingress.certmanager.tlsIssuer }}
    kind: ClusterIssuer
  commonName: {{ .Values.ingress.host }}
  dnsNames:
  - {{ .Values.ingress.host }}
  privateKey:
    algorithm: ECDSA
---
# IngressRoute https
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vikunja-https
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.ingress.host }}`) && (PathPrefix(`/api`) || PathPrefix(`/dav`) || PathPrefix(`/.well-known`))
    services:
    - name: {{ .Release.Name }}-api
      port: 80
      namespace: {{ .Release.Namespace }}
  - kind: Rule
    match: Host(`{{ .Values.ingress.host }}`)
    services:
    - name: {{ .Release.Name }}-frontend
      port: 80
      namespace: {{ .Release.Namespace }}
  tls:
    secretName: vikunja-secret