apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nocodb-externalsecret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: nocodb-secret
  data:
  - secretKey: postgres-password
    remoteRef:
      key: nocodb/db
      property: password
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: password
    remoteRef:
      key: nocodb/db
      property: password
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: NC_DB
    remoteRef:
      key: nocodb/db
      property: url
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: smtp-user
    remoteRef:
      key: nocodb/smtp
      property: username
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: smtp-password
    remoteRef:
      key: nocodb/smtp
      property: password
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue