#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/geek-cookbook/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/hay-kot/homebox
  # -- image tag
  tag: "v0.10.3"
  # -- image pull policy
  pullPolicy: IfNotPresent

env:
  HBOX_LOG_LEVEL: info
  HBOX_LOG_FORMAT: text
  HBOX_MAILER_HOST: "in-v3.mailjet.com"
  HBOX_MAILER_PORT: 587
  HBOX_MAILER_FROM: "noreply@miku.cx"
  HBOX_MAILER_PASSWORD:
    valueFrom:
        secretKeyRef:
            name: homebox-secret
            key: smtp-password
  HBOX_MAILER_USERNAME:
    valueFrom:
        secretKeyRef:
            name: homebox-secret
            key: smtp-user

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 7745

ingress:
  main:
    enabled: true
    annotations:
      # HTTPS as entry point
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      # Enable TLS
      traefik.ingress.kubernetes.io/router.tls: "true"
      # Enable cert-manager to create automatically the SSL certificate and store in Secret
      cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
      cert-manager.io/common-name: homebox.owo.ac

      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "homebox"
      gethomepage.dev/description: "Inventory and organization system built for the Home User!"
      gethomepage.dev/group: "Personal"
      gethomepage.dev/icon: "homebox.png"
    hosts:
      - host: homebox.owo.ac
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: homebox-tls
        hosts:
          - homebox.owo.ac

persistence:
  # -- Configure persistence for data to use sqlite backend.
  # @default -- See values.yaml
  data:
    enabled: true
    mountPath: /data
    accessMode: ReadWriteOnce
    size: 10Gi
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
      storageClassName: longhorn
