sshingress:
  enabled: true
  entrypoint: ssh

########################
# postgresql subchart
########################
postgresql:
  primary:
    podAnnotations:
      linkerd.io/inject: enabled
  auth:
    username: gitea
    database: gitea
    existingSecret: gitea-secret
  persistence:
    storageClass: longhorn
    size: 10Gi

########################
# gitea subchart
########################
gitea:
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: longhorn
    size: 100Gi
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    metrics:
      enabled: true
    podAnnotations:
      linkerd.io/inject: enabled
  postgresql:
    enabled: true
  memcached:
    enabled: true
