sshingress:
  enabled: true
  entrypoint: ssh

########################
# gitea subchart
########################
gitea:
  ingress:
    enabled: true
    annotations:
      # HTTPS as entry point
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      # Enable TLS
      traefik.ingress.kubernetes.io/router.tls: "true"
      # Enable cert-manager to create automatically the SSL certificate and store in Secret
      cert-manager.io/cluster-issuer: letsencrypt-staging-issuer
      cert-manager.io/common-name: gitea.owo.ac
    hosts:
      - host: gitea.owo.ac
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - gitea.owo.ac
        secretName: gitea-tls
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: longhorn
    size: 100Gi
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    additionalConfigFromEnvs:
      - name: ENV_TO_INI__LFS__STORAGE_TYPE
        value: local
      - name: ENV_TO_INI__PICTURE__GRAVATAR_SOURCE
        value: gravatar
      - name: ENV_TO_INI__MAILER__ENABLED
        value: true
      - name: ENV_TO_INI__MAILER__PROTOCOL
        value: smtp+starttls
      - name: ENV_TO_INI__MAILER__SMTP_ADDR
        value: in-v3.mailjet.com
      - name: ENV_TO_INI__MAILER__SMTP_PORT
        value: 587
      - name: ENV_TO_INI__MAILER__FROM
        value: noreply@miku.cx
      - name: ENV_TO_INI__MAILER__ENVELOPE_FROM
        value: noreply@miku.cx
      - name: ENV_TO_INI__MAILER__USER
        valueFrom:
          secretKeyRef:
            name: gitea-secret
            key: smtp-user
      - name: ENV_TO_INI__MAILER__PASSWD
        valueFrom:
          secretKeyRef:
            name: gitea-secret
            key: smtp-password
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    config:
      server:
        ENABLE_PPROF: true
    podAnnotations:
      linkerd.io/inject: enabled
  postgresql:
    enabled: true
  memcached:
    enabled: true
