#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/geek-cookbook/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: vikunja/vikunja
  # -- image tag
  tag: "0.23.0"
  # -- image pull policy
  pullPolicy: IfNotPresent

env:
  TZ: America/Vancouver
  VIKUNJA_SERVICE_PUBLICURL: "https://vikunja.owo.ac"
  VIKUNJA_DATABASE_DATABASE: vikunja
  VIKUNJA_DATABASE_TYPE: postgres
  VIKUNJA_DATABASE_HOST: vikunja-postgresql
  VIKUNJA_DATABASE_USER: vikunja
  VIKUNJA_MAILER_ENABLED: true
  VIKUNJA_MAILER_HOST: "in-v3.mailjet.com"
  VIKUNJA_MAILER_PORT: 587
  VIKUNJA_MAILER_USERNAME: d86fa73b53b9e7b67d3f8831be6329aa
  VIKUNJA_MAILER_FROMEMAIL: "noreply@miku.cx"
  VIKUNJA_SERVICE_ENABLEREGISTRATION: true
  VIKUNJA_MAILER_PASSWORD:
    valueFrom:
        secretKeyRef:
            name: vikunja-secret
            key: smtp-password
  VIKUNJA_DATABASE_PASSWORD:
    valueFrom:
        secretKeyRef:
          name: vikunja-secret
          key: postgres-password

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 3456

ingress:
  main:
    enabled: true
    annotations:
      # HTTPS as entry point
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      # Enable TLS
      traefik.ingress.kubernetes.io/router.tls: "true"
      # Enable cert-manager to create automatically the SSL certificate and store in Secret
      cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
      cert-manager.io/common-name: vikunja.owo.ac

      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Vijunja"
      gethomepage.dev/description: "The open-source, self-hostable to-do app."
      gethomepage.dev/group: "Personal"
      gethomepage.dev/icon: "vikunja.png"
    hosts:
      - host: vikunja.owo.ac
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: vikunja-tls
        hosts:
          - vikunja.owo.ac

persistence:
  # -- Configure persistence for data to use sqlite backend.
  # @default -- See values.yaml
  data:
    enabled: true
    mountPath: /app/vikunja/files
    accessMode: ReadWriteOnce
    size: 10Gi
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
      storageClassName: longhorn

########################
# postgresql subchart
########################
postgresql:
  auth:
    username: vikunja
    database: vikunja
    existingSecret: vikunja-secret
  persistence:
    storageClass: longhorn
    size: 10Gi
