# Ingress configuration
ingress:
  host: vikunja.owo.ac
  # configure cert-manager issuer
  certmanager:
    tlsIssuer: letsencrypt-prod-issuer

########################
# postgresql subchart
########################
postgresql:
  primary:
    podAnnotations:
      linkerd.io/inject: enabled
  auth:
    username: vikunja
    database: vikunja
    existingSecret: vikunja-secret
  persistence:
    storageClass: longhorn
    size: 10Gi

########################
# vikunja subchart
########################
vikunja:
  api:
    ingress:
      enabled: false
    service:
      timezone: America/Vancouver
    config:
      database: 
        type: postgres
      mailer:
        enabled: true
        host: "in-v3.mailjet.com"
        port: 587
        username: d86fa73b53b9e7b67d3f8831be6329aa
        fromemail: "noreply@miku.cx"
      service:
        enableregistration: true
    env:
      - name: VIKUNJA_SERVICE_FRONTENDURL
        value: https://vikunja.owo.ac/
      - name: VIKUNJA_DATABASE_USER
        value: vikunja
      - name: VIKUNJA_DATABASE_HOST
        value: vikunja-postgresql
      - name: VIKUNJA_DATABASE_DATABASE
        value: vikunja
      - name: VIKUNJA_DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: vikunja-secret
            key: password
      - name: VIKUNJA_MAILER_PASSWORD
        valueFrom:
          secretKeyRef:
            name: vikunja-secret
            key: smtp-password
    persistence:
      enabled: false
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: longhorn
  frontend:
    apiUrl: "https://vikunja.owo.ac/api/v1"
    image:
      repository: vikunja/frontend
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: "unstable"
    securityContext:
      allowPrivilegeEscalation: true
      runAsUser: 101 #nginx
      capabilities:
        drop:
        - ALL
        add:
        - NET_BIND_SERVICE
    ingress:
      enabled: false
  postgresqlEnabled: false
