########################
# postgresql subchart
########################
postgresql:
  primary:
    podAnnotations:
      linkerd.io/inject: enabled
  auth:
    username: vikunja
    database: vikunja
    existingSecret: vikunja-secret
  persistence:
    storageClass: longhorn
    size: 10Gi

########################
# vikunja subchart
########################
vikunja:
  api:
    ingress:
      enabled: false
    config:
      database: postgresql
      service:
        enableregistration: true
    envFrom:
      # Bind env variables from the secret
      - name: VIKUNJA_DATABASE_USER
        value: vikunja
      - name: VIKUNJA_DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: vikunja-secret
            key: password
      - name: VIKUNJA_DATABASE_HOST
        value: vikunja-postgresql
      - name: VIKUNJA_DATABASE_DATABASE
        value: vikunja
    persistence:
      enabled: false
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: longhorn
  frontend:
    image:
      repository: vikunja/frontend
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: "unstable"
    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      runAsUser: 1000
    ingress:
      enabled: false
  postgresqlEnabled: false
