

########################
# hajimari subchart
########################
hajimari:
  instanceName: hajimari
  defaultEnable: true
  name: Siyuan
  defaultSearchProvider:
    - name: Google
      token: g
      icon: simple-icons:google
      searchUrl: https://www.google.com/search?q={query}
      url: https://www.google.com
    - name: DuckDuckGo
      token: d
      icon: simple-icons:duckduckgo
      searchUrl: https://duckduckgo.com/?q={query}
      url: https://duckduckgo.com
  searchProviders:
  customApps:
  globalBookmarks: