image:
  # -- image repository
  repository: actualbudget/actual-server
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  # this example is not automatically updated, so be sure to use the latest image
  tag: sha-ae0faf4-alpine

# -- Configures service settings for the chart.
service:
  main:
    ports:
      http:
        port: 5006

ingress:
  main:
    enabled: true
    annotations:
      # HTTPS as entry point
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      # Enable TLS
      traefik.ingress.kubernetes.io/router.tls: "true"
      # Enable cert-manager to create automatically the SSL certificate and store in Secret
      cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
      cert-manager.io/common-name: actual.owo.ac
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Actual"
      gethomepage.dev/description: "Enjoy managing your finances"
      gethomepage.dev/group: "Personal"
      gethomepage.dev/icon: "actual.png"
    hosts:
      - host: actual.owo.ac
        paths:
          - path: /
            pathType: Prefix
    tls:
    - hosts:
        - actual.owo.ac
      secretName: actual-tls
persistence:
  data:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    storageClass: longhorn
    size: 2Gi
