## Chart values
sshingress:
  enabled: true
  entrypoint: ssh

image:
  repository: 1dev/server
  tag: 9.1.15

## Set this as true to stop OneDev server to perform various maintenance tasks such as backup, restore.
## Check https://code.onedev.io/onedev/manual/~files/main/pages/backup-restore.md for details
maintenance: false
nodeSelector:
  onedev:
    kubernetes.io/os: linux
  mysql:
    kubernetes.io/os: linux
service:
  main:
    port: 80
    loadBalancerSourceRanges: []
    annotations:
  ssh:
    separateService: false
    port: 22
    loadBalancerSourceRanges: []
    annotations:

## Ingress support, check below for more info.
## Check https://code.onedev.io/onedev/manual/~files/main/pages/deploy-into-k8s-with-helm.md#ingress-setup for details
ingress:
  host: "onedev.owo.ac"
  class: traefik
  homepage:
    enabled: true
    name: "Onedev"
    description: "Self-hosted Git Server with CI/CD and Kanban"
    group: "Development"
    icon: "onedev.png"
  annotations:
    # HTTPS as entry point
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # Enable TLS
    traefik.ingress.kubernetes.io/router.tls: "true"
    # Enable cert-manager to create automatically the SSL certificate and store in Secret
    cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
    cert-manager.io/common-name: onedev.owo.ac
  tls: true

onedev:
  admin:
    existingSecret: onedev-admin-secret
  storage:
    storageClassName: longhorn
    size: 100Gi
  resources:
    memory: 1024Mi

database:
  existingSecret: onedev-db-secret
  resources:
    memory: 256Mi
  storage:
    storageClassName: longhorn
    size: 20Gi

initial:
  serverUrl: ""  
  sshRootUrl: ""