
homepage:
  title: My Awesome Homepage
  base: https://homepage.owo.ac/
  config:
    bookmarks:
      - Developer:
          - Github:
              - abbr: GH
                href: https://github.com/
    services:
      - Infrastructure:
          - XOA:
              href: https://xoa.miku.cx/
              description: Xen Orchestra
              icon: xen-orchestra.png
          - DSM:
              href: https://nas.miku.cx/
              description: Synology DSM
              icon: synology-dsm.png
          - Opnsense:
              href: https://opn.miku.cx/
              description: Opnsense
              icon: opnsense.png
    widgets:
      - logo:
          icon: homepage.png
      - search:
          provider: custom
          url: https://search.owo.ac/?q=
          target: _blank
      - openmeteo:
          label: Burnaby
          latitude: 49.21
          longitude: -122.95
          timezone: America/Vancouver
          units: metric
          cache: 5
    kubernetes:
      mode: cluster
    settings:

  # The service account is necessary to allow discovery of other services
  serviceAccount:
    create: true
    name: homepage

  # This enables the service account to access the necessary resources
  enableRbac: true

  ingress:
    main:
      enabled: true
      annotations:
        # HTTPS as entry point
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        # Enable TLS
        traefik.ingress.kubernetes.io/router.tls: "true"
        # Enable cert-manager to create automatically the SSL certificate and store in Secret
        cert-manager.io/cluster-issuer: letsencrypt-staging-issuer
        cert-manager.io/common-name: homepage.owo.ac
      hosts:
        - host: homepage.owo.ac
          paths:
            - path: /
              pathType: Prefix