
homepage:
  image:
    repository: ghcr.io/benphelps/homepage
    tag: v0.6.16
  config:
    bookmarks:
      - Developer:
          - Github:
              - abbr: GH
                href: https://github.com/
    services:
      - Infrastructure:
        - XOA:
            href: https://xoa.miku.cx/
            description: Xen Orchestra
            icon: xen-orchestra.png
        - DSM:
            href: https://nas.miku.cx/
            description: Synology DSM
            icon: synology-dsm.png
      - Networking:
        - Opnsense:
            href: https://opn.miku.cx/
            description: Opnsense
            icon: opnsense.png
        - Switch:
            href: http://10.0.10.2
            description: Opnsense
            icon: netgear.png
    widgets:
      - logo:
          icon: homepage.png
      - search:
          provider: custom
          url: https://search.owo.ac/?q=
          target: _blank
      - openmeteo:
          label: Burnaby
          latitude: 49.21
          longitude: -122.95
          timezone: America/Vancouver
          units: metric
          cache: 5
    kubernetes:
      mode: cluster
    settings:
      title: My Awesome Homepage
      base: https://homepage.owo.ac/
      background: "https://raw.githubusercontent.com/r1cebank/nuwa/main/resource/Konachan.com%20-%20351121%20aircraft%20aqua_eyes%20aqua_hair%20clouds%20dress%20hatsune_miku%20long_hair%20night%20prinz_eugen1938%20sky%20stars%20thighhighs%20twintails%20vocaloid.jpg"
      backgroundOpacity: 0.5
      headerStyle: boxed
      layout:
        Infrastructure:
          style: row
          columns: 4
        Networking:
          style: row
          columns: 4
        Monitoring:
          style: row
          columns: 4
        Personal:
        Development:
        Tools:

  # The service account is necessary to allow discovery of other services
  serviceAccount:
    create: true
    name: homepage

  # This enables the service account to access the necessary resources
  enableRbac: true

  ingress:
    main:
      enabled: true
      annotations:
        # HTTPS as entry point
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        # Enable TLS
        traefik.ingress.kubernetes.io/router.tls: "true"
        # Enable cert-manager to create automatically the SSL certificate and store in Secret
        cert-manager.io/cluster-issuer: letsencrypt-staging-issuer
        cert-manager.io/common-name: homepage.owo.ac
      hosts:
        - host: homepage.owo.ac
          paths:
            - path: /
              pathType: Prefix