
homepage:
  title: My Awesome Homepage
  base: https://homepage.owo.ac/
  config:
    bookmarks:
      - Developer:
          - Github:
              - abbr: GH
                href: https://github.com/
    services:
      - Infrastructure:
          - XOA:
              href: https://xoa.miku.cx/
              description: Xen Orchestra
              icon: xen-orchestra.png
          - DSM:
              href: https://nas.miku.cx/
              description: Synology DSM
              icon: synology-dsm.png
          - Opnsense:
              href: https://opn.miku.cx/
              description: Opnsense
              icon: opnsense.png
      - My Second Group:
          - My Second Service:
              href: http://localhost/
              description: Homepage is the best

      - My Third Group:
          - My Third Service:
              href: http://localhost/
              description: Homepage is 😎
    widgets:
      - longhorn:
          # Show the expanded view
          expanded: true
          # Shows a node representing the aggregate values
          total: true
          # Shows the node names as labels
          labels: true
          # Show the nodes
          nodes: true
          include:
            - k3s-worker-0
            - k3s-worker-1
            - k3s-worker-2
      # show the kubernetes widget, with the cluster summary and individual nodes
      - kubernetes:
          cluster:
            show: true
            cpu: true
            memory: true
            showLabel: true
            label: "cluster"
          nodes:
            show: true
            cpu: true
            memory: true
            showLabel: true
      - search:
          provider: duckduckgo
          target: _blank
    kubernetes:
      mode: cluster
    settings:

  # The service account is necessary to allow discovery of other services
  serviceAccount:
    create: true
    name: homepage

  # This enables the service account to access the necessary resources
  enableRbac: true

  ingress:
    main:
      enabled: true
      annotations:
        # HTTPS as entry point
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        # Enable TLS
        traefik.ingress.kubernetes.io/router.tls: "true"
        # Enable cert-manager to create automatically the SSL certificate and store in Secret
        cert-manager.io/cluster-issuer: letsencrypt-staging-issuer
        cert-manager.io/common-name: homepage.owo.ac
      hosts:
        - host: homepage.owo.ac
          paths:
            - path: /
              pathType: Prefix