# Create annotated namespaces

# coder namespace
kind: Namespace
apiVersion: v1
metadata:
  name: coder
  annotations:
    linkerd.io/inject: enabled
---
# vaultwarden namespace
kind: Namespace
apiVersion: v1
metadata:
  name: vaultwarden
  annotations:
    linkerd.io/inject: enabled
