# Create annotated namespaces

# app namespace
kind: Namespace
apiVersion: v1
metadata:
  name: apps
  annotations:
    linkerd.io/inject: enabled
---
# n8n namespace
kind: Namespace
apiVersion: v1
metadata:
  name: n8n