---
- name: Add onedev chart repo
  kubernetes.core.helm_repository:
    name: onedev
    repo_url: "{{ onedev_chart_repo }}"

- name: Deploy onedev chart
  become: true
  kubernetes.core.helm:
    name: onedev
    release_namespace: onedev-system
    chart_ref: onedev/onedev
    create_namespace: true
    update_repo_cache: true
    wait: true
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    values:
      ingress:
        host: "{{ onedev_host }}"
        class: "{{ ingress_class }}"
        enableDefaultIssuer: false
        tls: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect-to-https@kubernetescrd
          cert-manager.io/cluster-issuer: "{{ ingress_issuer }}"
      resources:
        onedev:
          memory: 1024Mi
        mysql:
          memory: 256Mi
      volumes:
        onedev:
          storageClassName: "{{ k3s_storage_class }}"
          size: "{{ onedev_repo_storage_size }}"
        mysql:
          storageClassName: "{{ k3s_storage_class }}"
          size: "{{ onedev_sql_storage_size }}"
      secrets:
        mysql:
          password: "{{ onedev_sql_password }}"
      initial:
        ## Login name of administrator
        user: "{{ onedev_admin_username }}"
        ## Password of administrator
        password: "{{ onedev_admin_password }}"
        ## Email address of adminsitrator
        email: "{{ onedev_admin_email }}"

- name: Create IngressRouteTCP for ssh
  become: true
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    definition: |
      apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRouteTCP
      metadata:
        name: onedev-ssh
        namespace: onedev-system
      spec:
        entryPoints:
          - ssh
        routes:
          - match: HostSNI(`*`)
            services:
              - name: onedev
                port: 22
