{{- if .Values.ingress.host -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "onedev.fullname" . }}
  annotations:
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.ingress.homepage.enabled -}}
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: {{ .Values.ingress.homepage.name }}
    gethomepage.dev/description: {{ .Values.ingress.homepage.description }}
    gethomepage.dev/group: {{ .Values.ingress.homepage.group }}
    gethomepage.dev/icon: {{ .Values.ingress.homepage.icon }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ include "onedev.fullname" . }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "onedev.fullname" . }}
              port:
                number: 80
{{- end }}
