apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: onedev-admin-externalsecret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: onedev-admin-secret
  data:
  - secretKey: password
    remoteRef:
      key: onedev/admin
      property: password
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: username
    remoteRef:
      key: onedev/admin
      property: username
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
