apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "onedev.fullname" . }}
  labels:
    {{- include "onedev.labels" . | nindent 4 }}
    tier: onedev
  annotations:
    "helm.sh/resource-policy": keep
spec:
  {{- if .Values.volumes.onedev.storageClassName }}
  storageClassName: {{ .Values.volumes.onedev.storageClassName }}
  {{- end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.onedev.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "onedev.fullname" . }}-mysql
  labels:
    {{- include "onedev.labels" . | nindent 4 }}
    tier: mysql
  annotations:
    "helm.sh/resource-policy": keep
spec:
  {{- if .Values.volumes.mysql.storageClassName }}
  storageClassName: {{ .Values.volumes.mysql.storageClassName }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.mysql.size }}
