{{ if not .Values.database.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "onedev.fullname" . }}-db
stringData:
  password: {{ .Values.database.password }}
{{- end }}
{{ if not .Values.onedev.admin.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "onedev.fullname" . }}-admin
stringData:
  username: {{ .Values.onedev.admin.user }}
  password: {{ .Values.onedev.admin.password }}
{{- end }}