{{ if not .Values.secrets.mysql.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "onedev.fullname" . }}-db
stringData:
  password: {{ .Values.secrets.mysql.password }}
{{ -end }}
{{ if not .Values.initial.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "onedev.fullname" . }}-admin
stringData:
  username: {{ .Values.initial.user }}
  password: {{ .Values.initial.password }}
{{ -end }}