apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-externalsecret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: n8n-secret
  data:
  - secretKey: n8n-encryption-key
    remoteRef:
      key: n8n/worker
      property: encryption-key
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: postgres-password
    remoteRef:
      key: n8n/db
      property: password
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: password
    remoteRef:
      key: n8n/db
      property: password
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue