#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/geek-cookbook/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: r1cebank/webminidisc
  # -- image tag
  tag: "nightly"
  # -- image pull policy
  pullPolicy: Always

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: true
    annotations:
      # HTTPS as entry point
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      # Enable TLS
      traefik.ingress.kubernetes.io/router.tls: "true"
      # Enable cert-manager to create automatically the SSL certificate and store in Secret
      cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
      cert-manager.io/common-name: wmd.owo.ac

      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Webminidisc"
      gethomepage.dev/description: "Brings NetMD Devices to the Web"
      gethomepage.dev/group: "Tools"
      gethomepage.dev/icon: "https://raw.githubusercontent.com/r1cebank/webminidisc-mirror/mirror/public/MiniDisc512.png"
    hosts:
      - host: wmd.owo.ac
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: wmd-tls
        hosts:
          - wmd.owo.ac
