apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ryot-externalsecret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ryot-secret
  data:
  - secretKey: postgres-password
    remoteRef:
      key: ryot/db
      property: password
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: password
    remoteRef:
      key: ryot/db
      property: password
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: DATABASE_URL
    remoteRef:
      key: ryot/db
      property: url
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: VIDEO_GAMES_TWITCH_CLIENT_ID
    remoteRef:
      key: ryot/twitch
      property: client_id
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: VIDEO_GAMES_TWITCH_CLIENT_SECRET
    remoteRef:
      key: ryot/twitch
      property: client_secret
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
