---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bjw-s.common.lib.chart.names.fullname" . }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
data:
  bookmarks.yaml: {{- if .Values.bookmarks }} |
{{- .Values.bookmarks | toYaml | nindent 4}}
{{- else }} ""
{{- end }}
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: {{- if .Values.services }} |
{{- .Values.services | toYaml | nindent 4 }}
{{- else }} ""
{{- end }}
  settings.yaml: |
    title: My Awesome Homepage
    base: https://homepage.owo.ac/
    background: "https://raw.githubusercontent.com/r1cebank/nuwa/main/resource/Konachan.com%20-%20342584%20aiha-deko%20crying%20hatsune_miku%20long_hair%20school_uniform%20signed%20sky%20stars%20tears%20vocaloid.jpg"
    backgroundOpacity: 0.2
    headerStyle: boxed
    layout:
      Personal:
      Development:
      Tools:
      Infrastructure:
        style: row
        columns: 4
      Networking:
        style: row
        columns: 4
      Monitoring:
        style: row
        columns: 4
  widgets.yaml: {{- if .Values.widgets }} |
{{- .Values.widgets | toYaml | nindent 4 }}
{{- else }} ""
{{- end }}