---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bjw-s.common.lib.chart.names.fullname" . }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
data:
  bookmarks.yaml: |
    - Developer:
      - Github:
        - abbr: GH
          href: https://github.com/
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster

  services.yaml: |
    - Infrastructure:
      - XOA:
          href: https://xoa.miku.cx/
          description: Xen Orchestra
          icon: xen-orchestra.png
      - DSM:
          href: https://nas.miku.cx/
          description: Synology DSM
          icon: synology-dsm.png
    - Networking:
      - Opnsense:
          href: https://opn.miku.cx/
          description: Opnsense
          icon: opnsense.png
      - Switch:
          href: http://10.0.10.2
          description: Netgear internet switch
          icon: netgear.png
  settings.yaml: |
    title: My Awesome Homepage
    base: https://homepage.owo.ac/
    background: "https://raw.githubusercontent.com/r1cebank/nuwa/main/resource/Konachan.com%20-%20342584%20aiha-deko%20crying%20hatsune_miku%20long_hair%20school_uniform%20signed%20sky%20stars%20tears%20vocaloid.jpg"
    backgroundOpacity: 0.2
    headerStyle: boxed
    layout:
      Infrastructure:
        style: row
        columns: 4
      Networking:
        style: row
        columns: 4
      Monitoring:
        style: row
        columns: 4
      Personal:
      Development:
      Tools:
  widgets.yaml: |
    - logo:
        icon: homepage.png
    - search:
        provider: custom
        url: https://search.owo.ac/?q=
        target: _blank
    - openmeteo:
        label: Burnaby
        latitude: 49.21
        longitude: -122.95
        timezone: America/Vancouver
        units: metric
        cache: 5