---
# HTTPS Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    # HTTPS as entry point
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # Enable TLS
    traefik.ingress.kubernetes.io/router.tls: "true"
{{- if .Values.ingress.auth.enable }}
    # Use Basic Auth Midleware configured
    traefik.ingress.kubernetes.io/router.middlewares:
      {{ .Values.ingress.auth.middlewareNamespace }}-{{ .Values.ingress.auth.middlewareName }}@kubernetescrd
{{- end }}
    # Enable cert-manager to create automatically the SSL certificate and store in Secret
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certmanager.tlsIssuer }}
    cert-manager.io/common-name: {{ .Values.ingress.host }}
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.homepage.enabled -}}
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: {{ .Values.ingress.homepage.name }}
    gethomepage.dev/description: {{ .Values.ingress.homepage.description }}
    gethomepage.dev/group: {{ .Values.ingress.homepage.group }}
    gethomepage.dev/icon: {{ .Values.ingress.homepage.icon }}
    {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: longhorn-tls
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80