---
- name: Retrieve kubeconfig
  become: true
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~/.kube/k3s.yaml
    flat: true

- name: Update ip address of kube config
  ansible.builtin.replace:
    path: ~/.kube/k3s.yaml
    regexp: '(?:[0-9]{1,3}\.){3}[0-9]{1,3}'
    replace: "{{ hostvars[groups['k3s_master'][0]].ansible_default_ipv4.address }}"
  delegate_to: localhost
