---

# Velero daily backup schedule
- name: Create a daily backup schedule on velero
  become: true
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    definition: |
      apiVersion: velero.io/v1
      kind: Schedule
      metadata:
        name: velero-full-backup
        namespace: velero
      spec:
        schedule: "{{ velero_backup_schedule }}"
        template:
          hooks: {}
          excludedResources: {{ velero_backup_excluded_resources }}
          includedNamespaces:
            - "*"
          included_resources:
            - "*"
          includeClusterResources: true
          metadata:
            labels:
              type: "full"
              schedule: "daily"
          ttl: 720h0m0s
