---

- name: Setting up k3s prerequisites
  hosts: k3s_nodes
  remote_user: k3s
  gather_facts: true
  become: true
  roles:
    - role: prereq

- name: Setting up k3s with embedded etcd control plane first node
  hosts: k3s_master[0]
  remote_user: k3s
  gather_facts: true
  become: true
  roles:
    - role: install_k3s_control_0
    - role: enable_csi_snapshot

- name: Setting up k3s with embedded etcd control plane rest of node
  hosts: k3s_master,!k3s_master[0]
  serial: 1
  remote_user: k3s
  gather_facts: true
  become: true
  roles:
    - role: install_k3s_control_n

- name: Setting up k3s workers
  hosts: k3s_worker,k3s_longhorn
  remote_user: k3s
  gather_facts: true
  become: true
  roles:
    - role: install_k3s_worker

- name: Retrieve config from master node
  hosts: k3s_master[0]
  remote_user: k3s
  gather_facts: true
  roles:
    - role: retrieve_kubeconfig

- name: Apply k3s labels on nodes
  hosts: k3s_nodes
  remote_user: k3s
  gather_facts: true
  become: true
  roles:
    - role: apply_k3s_label
