{{- $passwordValue := (randAlphaNum 16) | quote }}
apiVersion: v1
kind: Secret
metadata:
  name: es-fluentd-user-file-realm
type: kubernetes.io/basic-auth
data:
  username: "fluentd"
  password: {{ $passwordValue }}
  roles: fluentd_role