{{- $passwordValue := (randAlphaNum 16) | quote }}
apiVersion: v1
kind: Secret
metadata:
  name: es-prometheus-user-file-realm
type: kubernetes.io/basic-auth
data:
  username: "prometheus"
  password: {{ $passwordValue }}
  roles: {{ "prometheus_role" | b64enc }}