kind: Secret
apiVersion: v1
metadata:
  name: es-prometheus-roles-secret
stringData:
  roles.yml: |-
    prometheus_role:
      cluster: [ 'monitor' ] 
      indices:
      - names: [ '*' ]
        privileges: [ 'indices:admin/aliases/get', 'indices:admin/mappings/get', 'indices:monitor/stats', 'indices:data/read/search' ]