---

- name: Git clone vaultwarden chart repo
  ansible.builtin.git:
    repo: "{{ vaultwarden_chart_repo }}"
    dest: /tmp/helm_repo/vaultwarden
    version: "{{ vaultwarden_chart_commit }}"

- name: Deploy vaultwarden chart from local path
  kubernetes.core.helm:
    name: vaultwarden
    release_namespace: vaultwarden
    chart_ref: /tmp/helm_repo/vaultwarden
    create_namespace: true
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    wait: true
    values:
      image:
        tag: "{{ vaultwarden_image_tag }}"
      domain: "https://{{ vaultwarden_host }}"
      adminToken: "{{ vaultwarden_admin_token }}"
      signupDomains: "{{ vaultwarden_signup_whitelist }}"
      ingress:
        enabled: true
        additionalAnnotations:
          traefik.ingress.kubernetes.io/router.middlewares: traefik-system-redirect-to-https@kubernetescrd
          cert-manager.io/cluster-issuer: "{{ ingress_issuer }}"
        nginxIngressAnnotations: false
        class: "{{ ingress_class }}"
        tlsSecret: "{{ vaultwarden_host }}-crt"
        hostname: "{{ vaultwarden_host }}"
      smtp:
        host: "{{ service_smtp_host }}"
        port: "{{ service_smtp_port }}"
        from: "{{ service_smtp_from }}"
        fromName: "Vault Administrator"
        username: "{{ service_smtp_username }}"
        password: "{{ service_smtp_password }}"
        acceptInvalidHostnames: true
        acceptInvalidCerts: true
        security: "off"
      storage:
        enabled: true
        size: "{{ vaultwarden_disk_size }}"
        class: "{{ k3s_storage_class }}"
      yubikey:
        enabled: true
        clientId: "{{ vaultwarden_yubikey_client_id }}"
        clientSecret: "{{ vaultwarden_yubikey_client_secret }}"
