{{- range $index, $service := .Values.services }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-{{ $service.name }}-http
  namespace: {{ $.Release.Namespace }}
subsets:
- addresses:
  # list all external ips for this service
  - ip: {{ $service.ip }}
  ports:
  - name: {{ $service.name }}
    port: {{ $service.source_port }}
    protocol: {{ $service.protocol }}
{{- end }}