{{- range $index, $service := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: external-{{ $service.name }}-http
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
  - name: {{ $service.name }}
    port: {{ $service.service_port }}
    protocol: {{ $service.protocol }}
    targetPort: {{ $service.source_port }}
  clusterIP: None
  type: ClusterIPs
{{- end }}