# Ingress configuration
ingress:
  host: coder.owo.ac
  homepage:
    enabled: true
    name: "Coder"
    description: "Your Self-Hosted Remote Development Platform"
    group: "Development"
    icon: "coder.png"
  annotations:
    # HTTPS as entry point
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # Enable TLS
    traefik.ingress.kubernetes.io/router.tls: "true"
    # Enable cert-manager to create automatically the SSL certificate and store in Secret
    cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
    cert-manager.io/common-name: coder.owo.ac

########################
# postgresql subchart
########################
postgresql:
  primary:
    podAnnotations:
      linkerd.io/inject: enabled
  auth:
    username: coder
    database: coder
    existingSecret: coder-secret
  persistence:
    storageClass: longhorn
    size: 10Gi

########################
# coder subchart
########################
coder:
  coder:
    ingress:
      enable: false
    env:
      - name: CODER_PG_CONNECTION_URL
        valueFrom:
          secretKeyRef:
            name: coder-secret
            key: url
      - name: CODER_ACCESS_URL
        value: "https://coder.owo.ac"
    podAnnotations:
      linkerd.io/inject: enabled
