---

- name: Git clone csi snapshot repo
  ansible.builtin.git:
    repo: "{{ external_snapshotter_repo }}"
    dest: /tmp/k8s_repo/external_snapshotter
    version: "{{ external_snapshotter_tag }}"

- name: Install the Snapshot CRDs
  ansible.builtin.command:
    cmd: kubectl create -f /tmp/k8s_repo/external_snapshotter/client/config/crd
  register: output
  changed_when: output.rc != 0

- name: Install the Common Snapshot Controller
  ansible.builtin.command:
    cmd: kubectl create -f /tmp/k8s_repo/external_snapshotter/deploy/kubernetes/snapshot-controller
  register: output
  changed_when: output.rc != 0
