#######
# K3S #
#######

# k3s version
k3s_version: v1.28.3+k3s2

# k3s shared token
k3s_token: "{{ vault.cluster.k3s.token }}"

# k3s config directory
k3s_config_directory: /etc/rancher/k3s

# kubelet configuration
k3s_kubelet_config: |
  apiVersion: kubelet.config.k8s.io/v1beta1
  kind: KubeletConfiguration
  shutdownGracePeriod: 30s
  shutdownGracePeriodCriticalPods: 10s
  resolvConf: /etc/k3s-resolv.conf

# Extra arguments for k3s server installation
k3s_server_extra_args: >-
  --write-kubeconfig-mode '0644'
  --disable 'servicelb'
  --disable 'traefik'
  --disable 'local-storage'
  --resolv-conf /etc/k3s-resolv.conf
  --kube-controller-manager-arg 'bind-address=0.0.0.0'
  --kube-proxy-arg 'metrics-bind-address=0.0.0.0'
  --kube-scheduler-arg 'bind-address=0.0.0.0'
  --kube-controller-manager-arg 'terminated-pod-gc-threshold=10'

# Extra arguments for k3s agent installation
k3s_worker_extra_args: >-
  --node-label 'node_type=worker'
  --resolv-conf /etc/k3s-resolv.conf
  --kube-proxy-arg 'metrics-bind-address=0.0.0.0'
