---
#######
# K3S #
#######

# k3s version
k3s_version: v1.26.3+k3s1

# k3s shared token
k3s_token: "{{ vault.cluster.k3s.token }}"

# k3s config directory
k3s_config_directory: /etc/rancher/k3s

# kubelet configuration
k3s_kubelet_config: |
  apiVersion: kubelet.config.k8s.io/v1beta1
  kind: KubeletConfiguration
  shutdownGracePeriod: 30s
  shutdownGracePeriodCriticalPods: 10s

# Extra arguments for k3s server installation
k3s_server_extra_args: >-
  --write-kubeconfig-mode '0644'
  --disable 'servicelb'
  --disable 'traefik'
  --disable 'local-storage'
  --resolv-conf '/etc/k3s-resolv.conf'
  --node-label 'k3s.owo.ac/nodetype=master'
  --node-taint 'node-role.kubernetes.io/master=true:NoSchedule'
  --kube-controller-manager-arg 'bind-address=0.0.0.0'
  --kube-proxy-arg 'metrics-bind-address=0.0.0.0'
  --kube-scheduler-arg 'bind-address=0.0.0.0'
  --kubelet-arg 'config=/etc/rancher/k3s/kubelet.config'
  --kube-controller-manager-arg 'terminated-pod-gc-threshold=10'

# Extra arguments for k3s agent installation
k3s_worker_extra_args: >-
  --node-label 'node_type=worker'
  --node-label 'k3s.owo.ac/nodetype=worker'
  --node-label 'node.longhorn.io/create-default-disk=config'
  --node-label 'node.longhorn.io/default-disks-config=[{"path":"{{ worker_attached_disk }}", "allowScheduling":true}]'
  --kubelet-arg 'config=/etc/rancher/k3s/kubelet.config'
  --kube-proxy-arg 'metrics-bind-address=0.0.0.0'

###########
# Traefik #
###########

# HTTP Basic auth credentials
traefik_basic_auth_user: "{{ vault.traefik.admin.user }}"
traefik_basic_auth_passwd: "{{ vault.traefik.admin.password }}"

# DNS cluster service end-points
traefik_dashboard_dns: "traefik.{{ dns_domain }}"
longhorn_dashboard_dns: "storage.{{ dns_domain }}"
kibana_dashboard_dns: "kibana.{{ dns_domain }}"
elasticsearch_dns: "elasticsearch.{{ dns_domain }}"
fluentd_dns: "fluentd.{{ dns_domain }}"
monitoring_dns: "monitoring.{{ dns_domain }}"
linkerd_dashboard_dns: "linkerd.{{ dns_domain }}"

###################
# Velero  Secrets #
###################

# Minio user, key and bucket
minio_velero_user: "{{ vault.minio.velero.user }}"
minio_velero_key: "{{ vault.minio.velero.key }}"

velero_secret_content: |
  [default]
  aws_access_key_id: "{{ minio_velero_user }}"
  aws_secret_access_key: "{{ minio_velero_key }}"

###################
# Longhorn Secrets#
###################

# Minio user, key and bucket
minio_longhorn_user: "{{ vault.minio.longhorn.user }}"
minio_longhorn_key: "{{ vault.minio.longhorn.key }}"

###################
# Logging Secrets #
###################

# Fluentd-fluentbit shared key
fluentd_shared_key: "{{ vault.logging.fluentd.shared_key }}"

# Elasticsearch 'elastic' user password
efk_elasticsearch_passwd: "{{ vault.logging.elasticsearch.password }}"

# Loki minio user, key and bucket
minio_loki_user: "{{ vault.minio.loki.user }}"
minio_loki_key: "{{ vault.minio.loki.key }}"

######################
# Monitoring Secrets #
######################

# Grafana admin user password
prometheus_grafana_password: "{{ vault.grafana.admin.password}}"

#######################
# Tracing Secrets     #
#######################

# Tempo minio user, key and bucket
minio_tempo_user: "{{ vault.minio.tempo.user }}"
minio_tempo_key: "{{ vault.minio.tempo.key }}"
minio_tempo_bucket: k3s-tempo
