---
# HTTPS Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coder-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.homepage.enabled }}
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: {{ .Values.ingress.homepage.name }}
    gethomepage.dev/description: {{ .Values.ingress.homepage.description }}
    gethomepage.dev/group: {{ .Values.ingress.homepage.group }}
    gethomepage.dev/icon: {{ .Values.ingress.homepage.icon }}
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=coder"
    {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: coder-tls
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: coder
                port:
                  number: 80
