gitops:
  repo: https://github.com/r1cebank/nuwa
  revision: main

# List of application corresponding to different sync waves
apps:
  # cloudflare-tunnel
  - name: cloudflare-tunnel
    namespace: cloudflare-tunnel
    path: argocd/extras/cloudflare-tunnel
    syncWave: 1
  # coder App
  - name: coder
    namespace: coder
    path: argocd/extras/coder
    syncWave: 1
  # vaultwarden
  - name: vaultwarden
    namespace: vaultwarden
    path: argocd/extras/vaultwarden
    syncWave: 1
  # onedev
  - name: onedev
    namespace: onedev
    path: argocd/extras/onedev
    syncWave: 1
  # # gitea
  # - name: gitea
  #   namespace: gitea
  #   path: argocd/extras/gitea
  #   syncWave: 1
  - name: searxng
    namespace: searxng
    path: argocd/extras/searxng
    syncWave: 1
  - name: homepage
    namespace: homepage
    path: argocd/extras/homepage
    syncWave: 1
  - name: joplin
    namespace: joplin
    path: argocd/extras/joplin
    syncWave: 1
  - name: actual
    namespace: actual
    path: argocd/extras/actual
    syncWave: 1
  - name: vikunja
    namespace: vikunja
    path: argocd/extras/vikunja
    syncWave: 1
  - name: nocodb
    namespace: nocodb
    path: argocd/extras/nocodb
    syncWave: 1
  - name: nextcloud
    namespace: nextcloud
    path: argocd/extras/nextcloud
    syncWave: 1
  - name: grocy
    namespace: grocy
    path: argocd/extras/grocy
    syncWave: 1
  - name: n8n
    namespace: n8n
    path: argocd/extras/n8n
    syncWave: 1
  # - name: firefly-iii
  #   namespace: firefly-iii
  #   path: argocd/extras/firefly-iii
  #   syncWave: 1
  - name: external-services
    namespace: external-services
    path: argocd/extras/external-services
    syncWave: 1