apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fireflyiii-externalsecret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: fireflyiii-secret
  data:
  - secretKey: cron-token
    remoteRef:
      key: fireflyiii/token
      property: cron
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: postgres-password
    remoteRef:
      key: fireflyiii/db
      property: password
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: password
    remoteRef:
      key: fireflyiii/db
      property: password
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: api-token
    remoteRef:
      key: fireflyiii/token
      property: api
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: smtp-user
    remoteRef:
      key: fireflyiii/smtp
      property: username
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: smtp-password
    remoteRef:
      key: fireflyiii/smtp
      property: password
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue