---
- name: Ensure htpasswd utility is installed
  package:
    name: "apache2-utils"
    state: "present"
    update_cache: true
  become: true

- name: htpasswd utility
  shell:
    cmd: >-
      htpasswd -nb {{ vault.traefik.admin.user }} {{ vault.traefik.admin.password }}
  register: htpasswd
  changed_when: false

- name: Set htpasswd pair
  set_fact:
    traefik_auth_htpasswd_pair: "{{ htpasswd.stdout }}"

- name: Create/update traefik/basic_auth credentials
  community.hashi_vault.vault_kv2_write:
    url: "https://{{ vault_dns }}"
    path: "traefik/basic_auth"
    data:
      htpasswd-pair: "{{ traefik_auth_htpasswd_pair }}"
    auth_method: token
    token: '{{ token_data | community.hashi_vault.vault_login_token }}'
