---

- name: Create {{ secret_group.key }} credentials
  community.hashi_vault.vault_kv2_write:
    url: "https://{{ vault_dns }}"
    path: "{{ secret_group.key }}/{{ secret.key }}"
    data: "{{ secret.value }}"
    auth_method: token
    token: '{{ token_data | community.hashi_vault.vault_login_token }}'
  loop: "{{ secret_group.value | dict2items }}"
  loop_control:
    loop_var: secret
