#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/geek-cookbook/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/ignisda/ryot
  # -- image tag
  tag: "v1.17.6"
  # -- image pull policy
  pullPolicy: IfNotPresent

env:
  WEB_INSECURE_COOKIE: false
  DATABASE_URL:
    valueFrom:
        secretKeyRef:
          name: ryot-secret
          key: DATABASE_URL

podSecurityContext:
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8000

podAnnotations:
    linkerd.io/inject: enabled

ingress:
  main:
    enabled: true
    annotations:
      # HTTPS as entry point
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      # Enable TLS
      traefik.ingress.kubernetes.io/router.tls: "true"
      # Enable cert-manager to create automatically the SSL certificate and store in Secret
      cert-manager.io/cluster-issuer: letsencrypt-staging-issuer
      cert-manager.io/common-name: ryot.owo.ac

      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Ryot"
      gethomepage.dev/description: "Roll your own tracker!"
      gethomepage.dev/group: "Personal"
      gethomepage.dev/icon: "https://raw.githubusercontent.com/IgnisDa/ryot/78d8e667a3a7e0e05f0812dea4b71be019edd41a/apps/frontend/public/icon-512x512.png"
    hosts:
      - host: ryot.owo.ac
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: ryot-tls
        hosts:
          - ryot.owo.ac

persistence:
  # -- Configure persistence for data to use sqlite backend.
  # @default -- See values.yaml
  data:
    enabled: true
    mountPath: /data
    accessMode: ReadWriteOnce
    size: 10Gi
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
      storageClassName: longhorn

########################
# postgresql subchart
########################
postgresql:
  primary:
    podAnnotations:
      linkerd.io/inject: enabled
  auth:
    username: ryot
    database: ryot
    existingSecret: ryot-secret
  persistence:
    storageClass: longhorn
    size: 10Gi