services:
  - name: synology-nas
    ip: 10.0.50.131
    source_port: 5000
    service_port: 80
    protocol: TCP
    ingress_domain: nas.owo.ac
  - name: arch-mirror
    ip: 10.0.60.109
    source_port: 80
    service_port: 80
    protocol: TCP
    ingress_domain: arch.owo.ac
  - name: netgear-switch
    ip: 10.0.10.2
    source_port: 80
    service_port: 80
    protocol: TCP
    ingress_domain: netgear.owo.ac