services:
  - name: synology-nas
    ip: 10.0.50.131
    source_port: 5000
    service_port: 80
    protocol: TCP
    ingress_domain: nas.owo.ac
    cluster_issuer: letsencrypt-prod-issuer
  - name: crafty-server
    ip: 10.0.60.20
    source_port: 80
    service_port: 80
    protocol: TCP
    ingress_domain: crafty.owo.ac
    cluster_issuer: letsencrypt-prod-issuer