---
- name: Download caddy
  become: true
  ansible.builtin.get_url:
    url: "{{ caddy_download_url }}"
    dest: /usr/bin/caddy
    mode: "a+x"

- name: Ensure group "caddy" exists
  become: true
  ansible.builtin.group:
    name: caddy
    system: true
    state: present

- name: Add the user "caddy" to primary group of 'caddy'
  become: true
  ansible.builtin.user:
    name: caddy
    groups: caddy,users
    home: /var/lib/caddy
    shell: /usr/sbin/nologin
    system: true


- name: Create systemd file
  become: true
  ansible.builtin.copy:
    dest: /etc/systemd/system/caddy.service
    owner: caddy
    group: caddy
    mode: "0644"
    content: |
      # caddy.service
      #
      # For using Caddy with a config file.
      #
      # Make sure the ExecStart and ExecReload commands are correct
      # for your installation.
      #
      # See https://caddyserver.com/docs/install for instructions.
      #
      # WARNING: This service does not use the --resume flag, so if you
      # use the API to make changes, they will be overwritten by the
      # Caddyfile next time the service is restarted. If you intend to
      # use Caddy's API to configure it, add the --resume flag to the
      # `caddy run` command or use the caddy-api.service file instead.

      [Unit]
      Description=Caddy
      Documentation=https://caddyserver.com/docs/
      After=network.target network-online.target
      Requires=network-online.target

      [Service]
      Type=notify
      User=caddy
      Group=caddy
      ExecStart=/usr/bin/caddy run --environ --config /var/lib/caddy/Caddyfile
      ExecReload=/usr/bin/caddy reload --config /var/lib/caddy/Caddyfile --force
      TimeoutStopSec=5s
      LimitNOFILE=1048576
      LimitNPROC=512
      PrivateTmp=true
      ProtectSystem=full
      AmbientCapabilities=CAP_NET_BIND_SERVICE

      [Install]
      WantedBy=multi-user.target


- name: Create caddyfile
  become: yes
  template:
    src: Caddyfile.j2
    dest: /var/lib/caddy/Caddyfile
    mode: "u=rw,g=r,o=r"

- name: Start caddy
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: caddy
    daemon_reload: true
