{{- if and .Values.ingress.enableDefaultIssuer .Values.letsencrypt.email -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "onedev.fullname" .}}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: {{ include "onedev.fullname" . }}-private-key
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress.class }}
{{- end }}
