tcpIngress:
  enabled: false
  entrypoint: ldap

###################
# openldap-stack subchart
###################
openldap-stack-ha:
  global:
    ldapDomain: owo.ac
    existingSecret: openldap-secret
  image:
    tag: 2.6.6-fix
    pullPolicy: IfNotPresent
  persistence:
    storageClass: longhorn
  ltb-passwd:
    enabled: false
  phpldapadmin:
    enabled: true
    ingress:
      annotations:
        # HTTPS as entry point
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        # Enable TLS
        traefik.ingress.kubernetes.io/router.tls: "true"
        # Enable cert-manager to create automatically the SSL certificate and store in Secret
        cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
        cert-manager.io/common-name: ldap.owo.ac
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "phpLDAPadmin"
        gethomepage.dev/description: "Web-based LDAP browser"
        gethomepage.dev/group: "Infrastructure"
        gethomepage.dev/icon: "phpldapadmin.png"
      hosts:
        - ldap.owo.ac