apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-externalsecret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authelia-secret
  data:
  - secretKey: JWT_TOKEN
    remoteRef:
      key: authelia/keys
      property: jwt_token
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: SESSION_ENCRYPTION_KEY
    remoteRef:
      key: authelia/keys
      property: session_encryption_key
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: STORAGE_ENCRYPTION_KEY
    remoteRef:
      key: authelia/keys
      property: storage_encryption_key
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: OIDC_HMAC_SECRET
    remoteRef:
      key: authelia/keys
      property: oidc_hmac_secret
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: OIDC_PRIVATE_KEY
    remoteRef:
      key: authelia/keys
      property: oidc_private_secret
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: LDAP_PASSWORD
    remoteRef:
      key: authelia/passwords
      property: ldap_password
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: SMTP_PASSWORD
    remoteRef:
      key: authelia/passwords
      property: smtp_password
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: STORAGE_PASSWORD
    remoteRef:
      key: authelia/passwords
      property: storage_password
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: authelia/passwords
      property: redis_password
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue    
  - secretKey: postgres-password
    remoteRef:
      key: authelia/passwords
      property: storage_password
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: password
    remoteRef:
      key: authelia/keys
      property: storage_password
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue