---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-oidc-externalsecret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authelia-oidc-secret
    template:
      data:
        configuration.yaml: |
          identity_providers:
            oidc:
              enabled: true
  data:
    - secretKey: password
      remoteRef:
        key: authelia/passwords
        property: storage_password
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue