---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-oidc-externalsecret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authelia-oidc-secret
    template:
      data:
        configuration.yaml: |
        identity_providers:
          oidc:
            enabled: true
            clients:
              - id: argocd
                description: Argo CD
                secret: '$pbkdf2-sha512$310000$c8p78n7pUMln0jzvd4aK4Q$JNRBzwAo0ek5qKn50cFzzvE9RXV88h1wJn5KGiHrD0YKtZaR/nCb2CJPOsKaPK0hjf.9yHxzQGZziziccp6Yng'  # The digest of 'insecure_secret'.
                public: false
                authorization_policy: two_factor
                redirect_uris:
                  - https://argocd.owo.ac/auth/callback
                scopes:
                  - openid
                  - groups
                  - email
                  - profile
                userinfo_signing_algorithm: none
              - id: argocd-cli
                description: Argo CD (CLI)
                public: true
                authorization_policy: two_factor
                redirect_uris:
                  - http://localhost:8085/auth/callback
                scopes:
                  - openid
                  - groups
                  - email
                  - profile
                  - offline_access
                userinfo_signing_algorithm: none
  data:
    - secretKey: password
      remoteRef:
        key: authelia/passwords
        property: storage_password
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue