---
# Longhorn daily backup schedule
- name: Create a daily backup schedule on longhorn
  become: true
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    definition: |
      apiVersion: longhorn.io/v1beta1
      kind: RecurringJob
      metadata:
        name: longhorn-full-backup
        namespace: longhorn-system
      spec:
        cron: "{{ longhorn_backup_cron }}"
        task: "backup"
        groups:
          - default
        retain: {{ longhorn_backup_retain }}
        concurrency: 2
        labels:
          type: "full"
          schedule: "daily"
