apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openldap-externalsecret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: openldap-secret
  data:
  - secretKey: LDAP_ADMIN_PASSWORD
    remoteRef:
      key: openldap/admin
      property: password
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: LDAP_CONFIG_ADMIN_PASSWORD
    remoteRef:
      key: openldap/admin
      property: config_password
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
