apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-externalsecret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitea-secret
  data:
  - secretKey: smtp-user
    remoteRef:
      key: gitea/smtp
      property: username
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: smtp-password
    remoteRef:
      key: gitea/smtp
      property: password
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue