## Set this as true to stop OneDev server to perform various maintenance tasks such as backup, restore.
## Check https://code.onedev.io/onedev/manual/~files/main/pages/backup-restore.md for details
maintenance: false

nodeSelector:
  onedev:
    kubernetes.io/os: linux
  mysql:
    kubernetes.io/os: linux

service:
  main:
    port: 80
    #nodePort:
    # type: ClusterIP
    # clusterIP: None
    #loadBalancerIP:
    #externalTrafficPolicy:
    #externalIPs:
    loadBalancerSourceRanges: []
    annotations:
  ssh:
    # If separateService is enabled, a separate service is created for SSH with the following options,
    # otherwise, a port for SSH will be added in the main service with the following options.
    separateService: false
    port: 22
    #nodePort:
    ## The following options are only useful when separateService is set to true
    # type: LoadBalancer
    # clusterIP: None
    #loadBalancerIP:
    #externalTrafficPolicy:
    #externalIPs:
    loadBalancerSourceRanges: []
    annotations:

## Ingress support, check below for more info.
## Check https://code.onedev.io/onedev/manual/~files/main/pages/deploy-into-k8s-with-helm.md#ingress-setup for details
ingress:
  ## Optionally specify dns name to access OneDev via ingress controller
  host: ""
  ## Whether or not to enable TLS for above host
  tls: false
  ## Will be used as ingressClassName of ingress spec to match controller
  class: nginx
  ## Set to false to disable the default certificate issuer from this chart if you want to use a custom one
  enableDefaultIssuer: true
  ## Custom annotations for the ingress
  annotations:
    # kubernetes.io/tls-acme: "true"
    # cert-manager.io/issuer: ""
    # cert-manager.io/cluster-issuer: ""
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"

letsencrypt:
  ## Specify an email here to enable LetsEncrypt.
  ## Check https://code.onedev.io/onedev./server/~files/main/pages/deploy-into-k8s-with-helm.md#letsencrypt-setup for details
  email: ""

resources:
  onedev:
    memory: 1024Mi
  mysql:
    memory: 256Mi

volumes:
  onedev:
    ## Optionally specify storage class of persistent volume to store OneDev data including git repositories and indexes. 
    ## Leave empty to use default storage class
    storageClassName: ""
    size: 100Gi
  mysql:
    ## Optionally specify storage class of persistent volume to store mysql data.
    ## Leave empty to use default storage class
    storageClassName: ""
    size: 20Gi

secrets:
  mysql:
    ## change mysql root password if desired
    password: changeit

## Specify OneDev initial settings to avoid manual setup
initial:
  ## Login name of administrator
  user: "" 
  ## Password of administrator
  password: "" 
  ## Email address of adminsitrator
  email: ""
  ## Server url will be ignored if ingress.host is specified above
  serverUrl: ""  
  sshRootUrl: ""

## Specify a local directory containing certificates to be trusted.
## Certificate should be in PEM format starting with
## -----BEGIN CERTIFICATE----- and ending with -----END CERTIFICATE-----
trustCerts: ""