{{- if .Values.tunnels.argocd.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-tunnel-externalsecret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-tunnel-secret
  data:
  - secretKey: tunnel-token
    remoteRef:
      key: argocd/tunnel/cloudflare
      property: token
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: tunnel-id
    remoteRef:
      key: argocd/tunnel/cloudflare
      property: id
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
{{- end }}
