{{- if .Values.tunnels.argocd.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflared-tunnel
  name: cloudflared-tunnel
  namespace: {{ .Values.tunnels.argocd.namespace }}
spec:
  selector:
    matchLabels:
      app: cloudflared-tunnel
  template:
    metadata:
      labels:
        app: cloudflared-tunnel
    spec:
      containers:
      - name: cloudflared-tunnel
        image: {{ .Values.tunnels.argocd.cloudflared.image }}
        imagePullPolicy: Always
        args: ["tunnel", "--no-autoupdate", "run", "--token=$(TUNNEL_TOKEN)"]
        env:
          - name: TUNNEL_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.tunnels.argocd.cloudflared.token.existingSecret }}
                key: tunnel-token
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
{{- end }}