{{- if .Values.tunnels.argocd.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Namespace }}
  name: {{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Namespace }}
  template:
    metadata:
      labels:
        app: {{ .Release.Namespace }}
    spec:
      containers:
      - name: {{ .Release.Namespace }}
        image: {{ .Values.tunnels.argocd.cloudflared.image }}
        imagePullPolicy: Always
        args: ["tunnel", "--no-autoupdate", "run", "--token=$(TUNNEL_TOKEN)"]
        env:
          - name: TUNNEL_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.tunnels.argocd.cloudflared.token.existingSecret }}
                key: tunnel-token
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
{{- end }}