{{- range $key, $value := .Values.tunnels }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $key }}-tunnel-externalsecret
  namespace: {{ $.Release.Namespace }}
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ $key }}-tunnel-secret
  data:
  - secretKey: tunnel-token
    remoteRef:
      key: {{ $key }}/tunnel
      property: token
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: tunnel-id
    remoteRef:
      key: {{ $key }}/tunnel
      property: id
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
{{ end }}