---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Namespace }}
  name: {{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Namespace }}
  template:
    metadata:
      labels:
        app: {{ .Release.Namespace }}
    spec:
      containers:
      {{- range $key, $value := .Values.tunnels }}
      - name: {{ $key }}-cloudflare-tunnel
        image: {{ $value.cloudflared.image }}
        imagePullPolicy: Always
        args: ["tunnel", "--no-autoupdate", "run", "--token=$(TUNNEL_TOKEN)"]
        env:
          - name: TUNNEL_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ $value.cloudflared.token.existingSecret }}
                key: tunnel-token
      {{ end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
