---
- name: Generate vault variables file
  hosts: localhost

  vars_prompt:
    - name: cloudflare_email
      prompt: Enter cloudflare account email
      private: false
    - name: cloudflare_api_key
      prompt: Enter cloudflare account api key
      private: true

  tasks:
    - name: Create random passwords
      ansible.builtin.set_fact:
        "{{ item }}": "{{ lookup('ansible.builtin.password', '/dev/null chars=ascii_letters,digits') }}"
      with_items:
        - k3s_token
        - minio_root_password
        - minio_longhorn_password
        - minio_velero_password
        - minio_loki_password
        - minio_tempo_password
        - traefik_basic_auth_password
        - fluentd_shared_key
        - grafana_admin_password
        - elasticsearch_admin_password
        - coder_db_password

    - name: Create templated strings
      ansible.builtin.set_fact:
        "{{ item.templateName }}": "{{ item.templateString }}"
      with_items:
        - templateName: coder_db_url
          templateString: "postgres://coder:{{ coder_db_password }}@coder-db-postgresql.coder.svc.cluster.local:5432/coder?sslmode=disable"

    - name: Generate vault file
      ansible.builtin.template:
        src: vars/vault.yml.j2
        dest: vars/vault.yml

    - name: Encrypt file
      ansible.builtin.command:
        cmd: ansible-vault encrypt --vault-password-file=./.vault/vault_pass.sh vars/vault.yml
