# Prometheus monitoring
serviceMonitor:
  enable: true
  release: monitoring

# Ingress configuration
ingress:
  host: linkerd.owo.ac
  # configure cert-manager issuer
  certmanager:
    tlsIssuer: letsencrypt-staging-issuer
    # tlsIssuer: ca
  # Enabling traefik basic authorization, reusing global middleware created for Traefik
  auth:
    enable: true
    middlewareName: forwardauth-authelia
    middlewareNamespace: authelia
  homepage:
    enabled: true
    name: "Linkerd"
    description: "Service mesh dashboard."
    group: "Monitoring"
    icon: "https://raw.githubusercontent.com/linkerd/linkerd2/main/web/app/img/favicon.png"

########################
# linkerd-viz subchart
########################

linkerd-viz:
  # Skip namespace creation
  installNamespace: false
  # External Prometheus
  prometheusUrl: http://monitoring-prometheus.monitoring.svc.cluster.local:9090
  prometheus:
    enabled: false
  # External Grafana
  grafana:
    url: monitoring-grafana.monitoring.svc.cluster.local
  # Disabling DNS rebinding protection
  dashboard:
    enforcedHostRegexp: .*
