# Prometheus monitoring
serviceMonitor:
  enable: true
  release: monitoring

# Ingress configuration
ingress:
  host: linkerd.owo.ac
  # configure cert-manager issuer
  certmanager:
    tlsIssuer: letsencrypt-staging-issuer
    # tlsIssuer: ca
  # Enabling traefik basic authorization, reusing global middleware created for Traefik
  basicAuth:
    enable: true
    middlewareName: basic-auth
    middlewareNamespace: traefik

########################
# linkerd-viz subchart
########################

linkerd-viz:
  # Skip namespace creation
  installNamespace: false
  # External Prometheus
  prometheusUrl: http://monitoring-prometheus.monitoring:9090
  prometheus:
    enabled: false
  # External Grafana
  grafanaUrl: http://monitoring-grafana.monitoring:3000
  # Disabling DNS rebinding protection
  dashboard:
    enforcedHostRegexp: .*
