apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: op-connect-externalsecret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: op-connect-secret
  data:
  - secretKey: token
    remoteRef:
      key: onepassword/connect
      property: token
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: op-credentials-json
    remoteRef:
      key: onepassword/connect
      property: op-credentials-json
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue