---

- name: Add longhorn chart repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: "https://charts.longhorn.io"

- name: Deploy Longhorn chart with custom setting
  become: true
  kubernetes.core.helm:
    name: longhorn
    release_namespace: longhorn-system
    chart_ref: longhorn/longhorn
    chart_version: "{{ longhorn_version }}"
    create_namespace: true
    update_repo_cache: true
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    values:
      defaultSettings:
        backupTarget: "{{ longhorn_backup_target }}"
        createDefaultDiskLabeledNodes: true
      longhornManager:
        nodeSelector:
          k3s.owo.ac/nodetype: longhorn
      longhornUI:
        nodeSelector:
          k3s.owo.ac/nodetype: longhorn
      longhornDriver:
        nodeSelector:
          k3s.owo.ac/nodetype: longhorn
