---

- name: Add longhorn chart repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: "https://charts.longhorn.io"

- name: Deploy Longhorn chart with custom setting
  become: true
  kubernetes.core.helm:
    name: longhorn
    release_namespace: longhorn-system
    chart_ref: longhorn/longhorn
    chart_version: "{{ longhorn_version }}"
    create_namespace: true
    update_repo_cache: true
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    values:
      defaultSettings:
        backupTarget: "{{ longhorn_backup_target }}"
        createDefaultDiskLabeledNodes: true
      longhornManager:
        nodeSelector:
          k3s.owo.ac/nodetype: worker
      longhornUI:
        nodeSelector:
          k3s.owo.ac/nodetype: worker
      longhornDriver:
        nodeSelector:
          k3s.owo.ac/nodetype: worker

# CSI VolumeSnapshot Associated With Longhorn Snapshot
- name: Create a VolumeSnapshot Associated With Longhorn Snapshot
  become: true
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    definition:
      kind: VolumeSnapshotClass
      apiVersion: snapshot.storage.k8s.io/v1
      metadata:
        name: longhorn-snapshot-vsc
      driver: driver.longhorn.io
      deletionPolicy: Delete
      parameters:
        type: snap

# CSI VolumeSnapshot Associated With Longhorn Backup
- name: Create a VolumeSnapshot Associated With Longhorn Backup
  become: true
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    definition:
      kind: VolumeSnapshotClass
      apiVersion: snapshot.storage.k8s.io/v1
      metadata:
        name: longhorn-backup-vsc
      driver: driver.longhorn.io
      deletionPolicy: Delete
      parameters:
        type: bak
