---

- name: Add nfs-subdir-external-provisioner chart repo
  kubernetes.core.helm_repository:
    name: nfs-subdir-external-provisioner
    repo_url: "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner"

- name: Deploy nfs-subdir-external-provisioner chart
  become: true
  kubernetes.core.helm:
    name: nfs-subdir-external-provisioner
    release_namespace: nfs-subdir-external-provisioner
    chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    create_namespace: true
    update_repo_cache: true
    wait: true
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    values:
      nfs:
        server: "{{ nfs_provisioner_server }}"
        path: "{{ nfs_provisioner_server_path }}"
