apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: full
  namespace: {{ .Release.Namespace }}
spec:
  schedule: 0 4 * * *
  template:
    hooks: {}
    excludedResources:
      - persistentvolumes
      - persistentvolumeclaims
      - backuptargets.longhorn.io
      - backupvolumes.longhorn.io
      - backups.longhorn.io
      - nodes.longhorn.io
      - volumes.longhorn.io
      - engines.longhorn.io
      - replicas.longhorn.io
      - backingimagedatasources.longhorn.io
      - backingimagemanagers.longhorn.io
      - backingimages.longhorn.io
      - sharemanagers.longhorn.io
      - instancemanagers.longhorn.io
      - engineimages.longhorn.io
    includedNamespaces:
      - '*'
    includedResources:
      - '*'
    includeClusterResources: true
    metadata:
      labels:
        type: 'full'
        schedule: 'daily'
    ttl: 720h0m0s
