{{- if .Values.acme.dns01.cloudflare.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-externalsecret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cloudflare-secret
  data:
  - secretKey: CLOUDFLARE_EMAIL
    remoteRef:
      key: secret/data/certmanager/cloudflare
      property: email
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
  - secretKey: CLOUDFLARE_API_KEY
    remoteRef:
      key: secret/data/certmanager/cloudflare
      property: api_key
      conversionStrategy: Default # ArgoCD sync issue
      decodingStrategy: None # ArgoCD sync issue
{{- end }}