apiVersion: v2
name: certmanager
version: 0.0.0
dependencies:
  - name: cert-manager
    version: v1.12.2
    repository: https://charts.jetstack.io
  - name: trust-manager
    version: v0.5.0
    repository: https://charts.jetstack.io
