apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: kc
spec:
  instances: 1
  db:
    vendor: postgres
    host: keycloak-postgresql
    usernameSecret:
      name: keycloak-secret
      key: username
    passwordSecret:
      name: keycloak-secret
      key: postgres-password
    database: keycloak
  ingress:
      enabled: false
  http:
    tlsSecret: keycloak-tls
  hostname:
    hostname: {{ .Values.ingress.host }}