#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/geek-cookbook/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: neosmemo/memos
    # -- image tag
  tag: 0.13
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 5230

podAnnotations:
    linkerd.io/inject: enabled

ingress:
  main:
    enabled: true
    annotations:
      # HTTPS as entry point
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      # Enable TLS
      traefik.ingress.kubernetes.io/router.tls: "true"
      # Enable cert-manager to create automatically the SSL certificate and store in Secret
      cert-manager.io/cluster-issuer: letsencrypt-staging-issuer
      cert-manager.io/common-name: memos.owo.ac

      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "memos"
      gethomepage.dev/description: "A lightweight, self-hosted memo hub."
      gethomepage.dev/group: "Personal"
      gethomepage.dev/icon: "memos.png"
    hosts:
      - host: memos.owo.ac
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: memos-tls
        hosts:
          - memos.owo.ac

persistence:
  # -- Configure persistence for data to use sqlite backend.
  # @default -- See values.yaml
  data:
    enabled: true
    mountPath: /var/opt/memos
    accessMode: ReadWriteOnce
    size: 10Gi
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
      storageClassName: longhorn
