---
- name: Add traefik chart repo
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: "https://traefik.github.io/charts"

- name: Deploy traefik chart with custom setting
  become: true
  kubernetes.core.helm:
    name: traefik
    release_namespace: traefik
    chart_ref: traefik/traefik
    create_namespace: true
    update_repo_cache: true
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    wait: true
    values:
      additionalArguments:
        - "--metrics.prometheus=true"
        - "--accesslog"
        - "--accesslog.format=json"
        - "--accesslog.filepath=/data/access.log"
      deployment:
        additionalContainers:
          - name: stream-accesslog
            image: busybox
            args:
              - /bin/sh
              - -c
              - tail -n+1 -F /data/access.log
            imagePullPolicy: Always
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /data
                name: data
      ports:
        ssh:
          port: 22
          expose: true
          protocol: TCP
      service:
        spec:
          loadBalancerIP: "{{ ingress_loadbalancer_ip }}"
      providers:
        kubernetesIngress:
          publishedService:
            enabled: true
        kubernetesCRD:
          enabled: true
          allowCrossNamespace: true
      ingressRoute:
        dashboard:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "{{ ingress_class }}"
            cert-manager.io/cluster-issuer: "{{ ingress_issuer }}"
          matchRule: Host(`{{ traefik_dashboard_host }}`)
          entryPoints:
            - websecure
          tls:
            secretName: "{{ traefik_dashboard_host }}-secret"

- name: Expose traefik prometheus service
  become: true
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    namespace: traefik
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: traefik-metrics
        namespace: traefik
        labels:
          app.kubernetes.io/instance: traefik
          app.kubernetes.io/name: traefik
          app.kubernetes.io/component: traefik-metrics
      spec:
        type: ClusterIP
        ports:
          - name: metrics
            port: 9100
            targetPort: metrics
            protocol: TCP
        selector:
          app.kubernetes.io/instance: traefik
          app.kubernetes.io/name: traefik

- name: Adding HTTPS redirect
  become: true
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: Middleware
      metadata:
        name: redirect-to-https
        namespace: traefik
      spec:
        redirectScheme:
          scheme: https
          permanent: true

- name: Apply TLS options
  become: true
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: TLSOption
      metadata:
        name: default
        namespace: traefik
      spec:
        minVersion: VersionTLS12
        cipherSuites:
          - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
          - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305

- name: Adding dashboard redirect
  become: true
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      metadata:
        name: dashboard-http
        namespace: traefik
      spec:
        entryPoints:
          - web
        routes:
          - kind: Rule
            match: Host(`{{ traefik_dashboard_host }}`)
            priority: 1
            middlewares:
              - name: redirect-to-https
                namespace: traefik
            services:
              - kind: TraefikService
                name: noop@internal
