---

- name: Create traefik ServiceMonitor
  become: true
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    namespace: monitoring
    definition:
      apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        labels:
          app: traefik
          release: kube-prometheus-stack
        name: traefik
        namespace: monitoring
      spec:
        jobLabel: app.kubernetes.io/name
        endpoints:
          - port: metrics
            path: /metrics
        namespaceSelector:
          matchNames:
            - traefik
        selector:
          matchLabels:
            app.kubernetes.io/instance: traefik
            app.kubernetes.io/name: traefik
            app.kubernetes.io/component: traefik-metrics
