# Ingress configuration
ingress:
  host: longhorn.owo.ac
  # configure cert-manager issuer
  certmanager:
    tlsIssuer: letsencrypt-prod-issuer
  # Enabling traefik basic authorization, reusing global middleware created for Traefik
  auth:
    enable: true
    middlewareName: forwardauth-authelia
    middlewareNamespace: authelia
  homepage:
    enabled: true
    name: "Longhorn"
    description: "Cloud-Native distributed storage"
    group: "Monitoring"
    icon: "longhorn.png"

# Backup S3 backend URL
backup:
  minioUrl: "https://s3.miku.cx"

# Prometheus servicemonitor configuration
serviceMonitor:
  enable: true
  release: monitoring

#####################
# longhorn subchart
#####################

longhorn:
  defaultSettings:
    backupTarget: "s3://k3s-longhorn@us-west-1/"
    backupTargetCredentialSecret: longhorn-minio-secret
    defaultDataPath: /mnt/longhorn
