# Ingress configuration
ingress:
  host: longhorn.owo.ac
  # configure cert-manager issuer
  certmanager:
    tlsIssuer: letsencrypt-prod-issuer
  # Enabling traefik basic authorization, reusing global middleware created for Traefik
  basicAuth:
    enable: true
    middlewareName: basic-auth
    middlewareNamespace: traefik

# Backup S3 backend URL
backup:
  minioUrl: "https://s3.miku.cx"

# Prometheus servicemonitor configuration
serviceMonitor:
  enable: true
  release: monitoring

#####################
# longhorn subchart
#####################

longhorn:
  defaultSettings:
    # Backup S3 configuration
    backupTarget: "s3://k3s-longhorn@us-west-1/"
    backupTargetCredentialSecret: longhorn-minio-secret
    defaultDataPath: /mnt/longhorn
