image:
  repository: nocodb/nocodb
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.109.4"

env:
  # -- Set the container timezone
  TZ: America/Vancouver
  NC_SMTP_FROM: "noreply@miku.cx"
  NC_SMTP_HOST: "in-v3.mailjet.com"
  NC_SMTP_PORT: 587
  NC_ADMIN_EMAIL: "siyuan@owo.ac"
  NC_ADMIN_PASSWORD:
    valueFrom:
        secretKeyRef:
          name: nocodb-secret
          key: NC_ADMIN_PASSWORD
  NC_SMTP_USERNAME:
    valueFrom:
      secretKeyRef:
        name: nocodb-secret
        key: NC_SMTP_USERNAME
  NC_SMTP_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: nocodb-secret
        key: NC_SMTP_PASSWORD
  NC_DB:
    valueFrom:
      secretKeyRef:
        name: nocodb-secret
        key: NC_DB
service:
  main:
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: true
    annotations:
      # HTTPS as entry point
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      # Enable TLS
      traefik.ingress.kubernetes.io/router.tls: "true"
      # Enable cert-manager to create automatically the SSL certificate and store in Secret
      cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
      cert-manager.io/common-name: nocodb.owo.ac

      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Nocodb"
      gethomepage.dev/description: "Open Source Airtable Alternative"
      gethomepage.dev/group: "Tools"
      gethomepage.dev/icon: "nocodb.png"
    hosts:
      - host: nocodb.owo.ac
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: nocodb-tls
        hosts:
          - nocodb.owo.ac

persistence:
  # -- Configure persistence for data to use sqlite backend.
  # @default -- See values.yaml
  data:
    enabled: true
    mountPath: /usr/app/data/
    accessMode: ReadWriteOnce
    size: 10Gi
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
      storageClassName: longhorn

# -- Enable and configure postgresql database subchart under this key.
#    For more options see [postgresql chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/postgresql)
# @default -- See values.yaml
postgresql:
  enabled: true
  auth:
    username: nocodb
    database: nocodb
    existingSecret: nocodb-secret
  architecture: standalone
  primary:
    persistence:
      enabled: true
      storageClass: "longhorn"
      size: 10Gi
